services:
  # Database
  - type: web
    name: moneygram-db
    plan: free
    disk:
      name: postgres-disk
      mountPath: /var/lib/postgresql/data
    env:
      - key: DATABASE_URI
        value: sqlite:///app.db

  # Backend Web Service
  - type: web
    name: moneygram-backend
    env: python
    buildCommand: "pip install -r requirements.txt && flask db upgrade"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: DATABASE_URI
        fromService:
          type: web
          name: moneygram-db
          envVar: DATABASE_URL
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src/server